### ISSUE TITLE
Display custom message when several arguments are indicated

### ISSUE THREAD

**Issue by helmasaur** [Helmasaur/Bioman#2]
When several arguments are indicated on a command which requires one, a custom message should be displayed.

Example:
<img width="682" alt="capture d ecran 2016-12-18 a 15 08 28" src="https://cloud.githubusercontent.com/assets/873762/21294038/4ec6af86-c534-11e6-9571-9a2c54dec5b5.png">

**Comment by Helmasaur** [comment]
Seems fixed but I don't know since when.

**Comment by helmasaur** [comment]
Seems fixed but I don't know since when.
